---
abstract: 'Perl client for the proxies created by the Browsermob server'
author:
  - 'Daniel Gempesaw <gempesaw@gmail.com>'
build_requires:
  DDP: '0'
  Data::Dumper: '0'
  Net::HTTP::Spore::Middleware::Mock: '0'
  Net::Ping: '0'
  Test::LWP::UserAgent: '0'
  Test::More: '0'
  Try::Tiny: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.014, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Browsermob-Proxy
requires:
  Carp: '0'
  IO::Socket::INET: '0'
  JSON: '0'
  LWP::UserAgent: '0'
  Moo: '0'
  Net::HTTP::Spore: '0'
  Net::HTTP::Spore::Middleware::DefaultParams: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/gempesaw/Browsermob-Proxy/issues
  repository: git://github.com/gempesaw/Browsermob-Proxy.git
version: '0.05'
